version: '3.8'

services:
  postgres-itree:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-itree
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: itree_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: