[project]
name = "itree"
version = "0.1.0"
description = "itree extension python support"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg>=3.2.9",
    "pytest>=8.3.5",
    "sqlalchemy>=2.0.41",
]
